# Generated by Django 5.1.3 on 2024-11-15 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reagents', '0002_alter_protocol_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocol',
            name='upload',
        ),
    ]
