# Generated by Django 4.2.7 on 2024-02-14 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagents', '0002_cellline'),
    ]

    operations = [
        migrations.AddField(
            model_name='reagent',
            name='reagent_supplier',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
