# Generated by Django 5.1.3 on 2024-11-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reagents', '0004_experiment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.CharField(max_length=64)),
                ('protocol_name', models.CharField(max_length=64)),
                ('protocol_file', models.FileField(blank=True, upload_to='entries/docx')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
