# Generated by Django 5.1.3 on 2024-11-18 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reagents', '0005_rename_protocol_uploadfile_experiment_upload'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadFile',
            new_name='Protocol',
        ),
    ]
